app:
  name: spctest
  project: updatetest
  owner: shaun coleman
  email: scoleman@infoblox.com
  projecturl: xxx
  helmrepo: not yet included
  jiraProject: xx:testesd
  components:
    component:
      name: test-csp
      gitrepo: https://github.com/scoleman-ib/play_test
      filepath: testapp/test-csp-success
      imagerepo: scolemanib/test
    component:
      name: test-csp-delayed-jobs
      gitrepo: https://github.com/scoleman-ib/play_test
      filepath:  testapp/test-csp-delayed-jobs-success
      imagerepo: ---
dev:
  test-csp:
    resources:
      test1: dev1
      test2: dev2res
    secret:
      test1: devsec
      test2: dev2sec_Updated
    config:
      test1: devconf
      test2: dev2conf
  test-csp-delayed-jobs:
    resources:
      test1: dev1
      test2: dev2res
    secret:
      test1: devsec
      test2: dev2sec
preprod:
   test-csp:
     config:
       test1: preprodconf
       test3: preprodconf3
