app:
  name: spctest
  project: updatetest
  owner: shaun coleman
  email: scoleman@infoblox.com
  projecturl: xxx
  helmrepo: xxx
  jiraProject: xx:xyyzq
  components:
    component:
      name: test-csp
      gitrepo: https://github.com/scoleman-ib/play_test
      filepath: testapp/test-csp
      imagerepo: scolemanib/test
    component:
      name: test-csp-delayed-jobs
      gitrepo: https://github.com/scoleman-ib/play_test
      filepath:  testapp/test-csp-delayed-jobs
      imagerepo: scolemanib/test
dev:
  test-csp:
    resources:
      test1: devres
      test2: dev2res
    secret:
      test1: devsec
      test2: dev2sec
    config:
      test1: devconf
      test2: dev2conf
  test-csp-delayed-jobs:
    resources:
      test1: devres
      test2: dev2res
    secret:
      test1: devsec
      test2: dev2sec
