app:
  name: spctest
  owner: shaun coleman
  email: scoleman@infoblox.com
  gitrepo: https://github.com/scoleman-ib/play_test
  jiraProject: xx:xxi
  components:
    component:
      name: test-csp
      image: 12312
      tag:  123123
    component:
      name: test-csp-delayed-jobs
      image: 2323
      tag:  234234
dev:
  test-csp:
    resources:
      test1: devres
      test2: dev2res
    secret:
      test1: devsec
      test2: dev2sec
    config:
      test1: devconf
      test2: dev2conf
  test-csp-delayed-jobs:
    resources:
      test1: devres
      test2: dev2res
    secret:
      test1: devsec
      test2: dev2sec
