app:
  name: new_testapp
  project: new_updatetest
  owner: shaun coleman
  email: scoleman@infoblox.com
  projecturl: xxx
  helmrepo: not yet included
  jiraProject: xx:comptest
    component:
      name: test-comp
      gitrepo: https://github.com/scoleman-ib/play_test
      filepath: testapp/test-comp
      imagerepo: scolemanib/test
    component:
      name: test-comp-two
      gitrepo: https://github.com/scoleman-ib/play_test
      filepath:  testapp/test-comp-delayed
      imagerepo: scolemanib/test
dev:
  test-comp:
    resources:
      resource_test: devre_Updated2
      resource_test2: devres2_new
    secret:
      sec_test: devsec
      sec_test2: devsec2
    config:
      config_test: devconf_demo
      config_test2: devconf2_demo
  test-comp-two:
    resources:
      resource_test_del: two_res
      resource_test_del2: two_res2
    secret:
      sec_test_del: two_sec_new
      sec_test_del2: two_sec2_new
